[global]
[template]

[[template.pass]]
role = 'parent'
path = ''
cmd = 'make insmod'

[[template.pass]]
role = 'child'
path = ''
cmd = 'make insmod'

[[template.pass]]
role = 'child'
path = 'exp'
cmd = 'sleep 3; ./connector -gid=${parent_gid} -mac_id=${@incr} -nic_id=0'

[[template.pass]]
role = 'parent'
path = 'exp/fork-functions'
cmd = 'cd ${micro_func_name} && python function.py -exclude_execution=1 -pin=1 -profile=0 -handler_id=73'

[[template.pass]]
role = 'child'
path = ''
cmd = 'sleep 3 && make bench_lean_mitosis mac_id=${@incr} LEAN_APP_NAME=simple_child'


[template.placeholder]
micro_func_name = [
#    "micro", 
#    "json", 
#    "chameleon", 
#    "compression", 
#    "helloworld", 
#    "image", 
    "pagerank", 
#    "pyaes",
#    "recognition"
]


